# Generated by Django 2.2 on 2019-04-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='tid',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
