# Generated by Django 2.1.7 on 2019-04-01 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Usertype'),
        ),
    ]
