# Generated by Django 2.1.2 on 2018-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20181212_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone',
            field=models.IntegerField(default=12345, max_length=12),
        ),
    ]
