# Generated by Django 2.0.9 on 2019-05-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funds',
            name='event',
        ),
    ]
