# Generated by Django 2.1.3 on 2019-05-02 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profilePic',
        ),
    ]
