# Generated by Django 2.1.2 on 2019-04-30 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20190425_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='User_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
