# Generated by Django 2.1.2 on 2019-05-01 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_auto_20190501_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Date',
            field=models.DateField(default=datetime.date(2019, 5, 1)),
        ),
    ]
