# Generated by Django 2.1.2 on 2019-05-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Payment_Done',
            field=models.BooleanField(default=False),
        ),
    ]
