# Generated by Django 2.1.2 on 2019-05-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20190430_2043'),
        ('package', '0005_booking_payment_done'),
        ('package', '0004_coustomize_package'),
    ]

    operations = [
    ]
