# Generated by Django 2.0.6 on 2019-03-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint_Check',
        ),
    ]
