# Generated by Django 2.2 on 2019-05-01 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileorfolder',
            fields=[
                ('file_name', models.CharField(max_length=100)),
                ('file_hash', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('file_size', models.IntegerField()),
                ('number_peers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer', models.CharField(max_length=16)),
                ('file_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesharing.fileorfolder')),
            ],
        ),
        migrations.CreateModel(
            name='chunkshash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunks', models.CharField(max_length=500)),
                ('offset', models.IntegerField()),
                ('file_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filesharing.fileorfolder')),
            ],
        ),
    ]
