# Generated by Django 2.2 on 2019-05-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chunkshash',
            new_name='chunkshashdb',
        ),
    ]
