# Generated by Django 2.2 on 2019-05-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filesharing', '0003_auto_20190501_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
