# Generated by Django 2.1.7 on 2019-04-30 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0010_auto_20190414_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(max_length=16)),
                ('credits', models.IntegerField(max_length=5000)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.Party')),
            ],
        ),
    ]
