# Generated by Django 2.1.7 on 2019-04-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_auto_20190430_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='card_number',
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='credits',
            field=models.FloatField(null=True),
        ),
    ]
