# Generated by Django 2.1.7 on 2019-04-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20190430_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Party'),
        ),
    ]
