# Generated by Django 2.1.7 on 2019-04-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_auto_20190430_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentdetails',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
