# Generated by Django 2.1.7 on 2019-04-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0007_auto_20190430_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='credits',
            new_name='amount',
        ),
    ]
