# Generated by Django 2.1.7 on 2019-05-01 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20190414_1713'),
        ('party', '0008_auto_20190430_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretKey',
            fields=[
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.Party')),
                ('sk', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
