module.exports = [
    {
        name:'Delhi',
        short_form:'DEL'
    },
    {
        name:'Bombay',
        short_form:'BOM'
    },
    {
        name:'Chennai',
        short_form:'MAA'
    },
    {
        name:'Kolkata',
        short_form:'KOL'
    },
    {
        name:'Lucknow',
        short_form:'LKW'
    },
    {
        name:'Patna',
        short_form:'PTN'
    },
    {
        name:'Haryana',
        short_form:'HRY'
    },
    {
        name:'Jharkhand',
        short_form:'JHK'
    },
    {
        name:'Goa',
        short_form:'GOA'
    },
    {
        name:'Gowhati',
        short_form:'GWH'
    },
    {
        name:'Kerela',
        short_form:'KRL'
    },
];
