# Generated by Django 2.1.7 on 2019-04-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
    ]
