# Generated by Django 2.1.7 on 2019-04-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_party_id'),
        ('authentication', '0002_auto_20190405_1447'),
    ]

    operations = [
    ]
