# Generated by Django 2.1.7 on 2019-04-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_merge_20190405_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
