# Generated by Django 2.1.7 on 2019-04-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190405_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
