# Generated by Django 2.1.7 on 2019-04-07 05:39

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_affiliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.PositiveIntegerField(null=True, validators=[authentication.models.phone_number_validation]),
        ),
    ]
