# Generated by Django 2.1.7 on 2019-04-07 05:49

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20190407_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.BigIntegerField(null=True, validators=[authentication.models.phone_number_validation]),
        ),
    ]
