# Generated by Django 2.1.7 on 2019-04-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20190407_1155'),
        ('authentication', '0007_auto_20190407_1119'),
    ]

    operations = [
    ]
