# Generated by Django 2.0.9 on 2019-05-01 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('donationid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('transactionid', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=10)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventid', models.AutoField(primary_key=True, serialize=False)),
                ('requestedorganization', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('', 'Select Type'), ('1', 'education'), ('2', 'NGO'), ('3', 'desasters')], max_length=50)),
                ('subtype', models.CharField(choices=[('', 'Select Subtype'), ('1', 'books'), ('2', 'money')], max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('verifierassigned', models.CharField(max_length=10, null=True)),
                ('status', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
                ('requesteddate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField()),
                ('img', models.ImageField(blank=True, upload_to='images')),
                ('requesteditem', models.CharField(max_length=10)),
                ('requestedquantity', models.PositiveIntegerField(default=0)),
                ('costperitem', models.PositiveIntegerField(default=0)),
                ('itemsremaining', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Events_Supported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('subtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Event'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cart',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Event'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
