# Generated by Django 2.0.9 on 2019-05-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='subtype',
            field=models.CharField(choices=[('', 'Select Subtype'), ('1', 'stationary'), ('2', 'support')], max_length=50),
        ),
    ]
