# Generated by Django 2.1.4 on 2019-04-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booked_tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_seat_no', models.TextField()),
                ('ticket_book_from', models.CharField(max_length=50)),
                ('ticket_booking_website', models.CharField(max_length=100)),
                ('ticket_booking_tranc_id', models.CharField(max_length=100)),
                ('ticket_booking_username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('ticked_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='changes_on_theaters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_id', models.CharField(max_length=50)),
                ('last_change', models.DateTimeField()),
                ('change_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_release_date', models.DateField()),
                ('movie_age_rating', models.CharField(max_length=100)),
                ('movie_duration_mins', models.CharField(max_length=100)),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_actors', models.CharField(max_length=100)),
                ('movie_directors', models.CharField(max_length=100)),
                ('movie_producers', models.CharField(max_length=100)),
                ('movie_writers', models.CharField(max_length=100)),
                ('imdb_movie_rating', models.CharField(max_length=50)),
                ('movie_description', models.TextField()),
                ('movie_trailer_link', models.CharField(max_length=100)),
                ('movie_poster_1', models.ImageField(blank=True, upload_to='poster_1')),
                ('movie_poster_2', models.ImageField(blank=True, upload_to='poster_2')),
            ],
        ),
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_no', models.CharField(max_length=5)),
                ('seat_string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=50)),
                ('adressline1', models.CharField(max_length=50)),
                ('adressline2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('theatre_rating', models.CharField(max_length=50)),
                ('theatre_merchant_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_price_and_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_timings', models.TimeField()),
                ('date', models.DateField()),
                ('seat_class', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movie_and_cinema_data.movie')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_and_cinema_data.screen')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_price_and_time_id', models.CharField(max_length=50)),
                ('last_change', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_and_cinema_data.theatre'),
        ),
        migrations.AddField(
            model_name='booked_tickets',
            name='movie_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_and_cinema_data.ticket_price_and_time'),
        ),
    ]
