# Generated by Django 2.1.4 on 2019-04-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_and_cinema_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='changes_on_screens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_id', models.CharField(max_length=50)),
                ('last_change', models.DateTimeField()),
                ('change_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='theatre',
            name='no_of_screens',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
