# Generated by Django 2.1.4 on 2019-04-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_and_cinema_data', '0002_auto_20190422_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.CharField(max_length=50)),
                ('last_change', models.DateTimeField()),
            ],
        ),
    ]
