# Generated by Django 2.1.8 on 2019-04-17 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_phone', models.CharField(max_length=10)),
                ('cust_house_no', models.CharField(blank=True, max_length=10)),
                ('cust_street', models.CharField(blank=True, max_length=100)),
                ('cust_city', models.CharField(blank=True, max_length=50)),
                ('cust_zipcode', models.CharField(blank=True, max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
