# Generated by Django 2.1.8 on 2019-04-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20190427_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='cust_street',
            new_name='cust_address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cust_house_no',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
