# Generated by Django 2.2 on 2019-04-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blood_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate_blood',
            name='Amount_blood_received',
        ),
        migrations.RemoveField(
            model_name='donate_blood',
            name='email',
        ),
        migrations.AddField(
            model_name='donate_blood',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='donate_blood',
            name='img',
            field=models.ImageField(default='/home/hemanth/Pictures/profile_pic1.jpeg', upload_to='blog_pics'),
        ),
    ]
