# Generated by Django 2.1.1 on 2019-04-30 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_name', models.CharField(blank=True, max_length=10)),
                ('flight_code', models.CharField(blank=True, max_length=10)),
                ('dept_city', models.CharField(blank=True, max_length=10)),
                ('dept_time', models.TimeField()),
                ('no_of_stops', models.CharField(blank=True, max_length=10)),
                ('reach_time', models.TimeField()),
                ('duration', models.CharField(max_length=100)),
                ('arrival_city', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('book_date', models.DateTimeField(blank=True, null=True)),
                ('details', models.CharField(max_length=100)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('price', models.CharField(max_length=10)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('booking_date', models.DateTimeField(blank=True, null=True)),
                ('details', models.CharField(max_length=500)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
