# Generated by Django 2.1.7 on 2019-05-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
