# Generated by Django 2.2 on 2019-04-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_auto_20190425_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Fare',
            field=models.IntegerField(null=True),
        ),
    ]
