# Generated by Django 2.1.3 on 2019-04-14 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='date',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_title',
        ),
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.CharField(max_length=60, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='package',
            name='money',
            field=models.DecimalField(decimal_places=6, max_digits=18, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='package',
            name='no_of_days',
            field=models.DecimalField(decimal_places=0, max_digits=18, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='package',
            name='origin',
            field=models.CharField(max_length=60, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='package',
            name='package_id',
            field=models.CharField(max_length=60, null='true'),
            preserve_default='true',
        ),
        migrations.AddField(
            model_name='package',
            name='user_id',
            field=models.CharField(max_length=60, null='true'),
            preserve_default='true',
        ),
    ]
