# Generated by Django 2.1.7 on 2019-05-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0013_auto_20190501_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='B94CBCED850A', max_length=14),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='ADDA8F4C1E1F', max_length=14),
        ),
    ]
