# Generated by Django 2.1.7 on 2019-05-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0014_auto_20190501_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='C4BBDB74310F', max_length=14),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='ADD00D9663FC', max_length=14),
        ),
    ]
