# Generated by Django 2.2 on 2019-04-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Subject', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=255)),
            ],
        ),
    ]
