# Generated by Django 2.2 on 2019-04-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
