# Generated by Django 2.1.3 on 2019-05-01 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GENRE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languages', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('Review', models.CharField(max_length=1000)),
                ('edited', models.BooleanField(default=False)),
                ('date_reviewed', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleName', models.CharField(max_length=120)),
                ('releaseDate', models.DateField()),
                ('storyLine', models.CharField(max_length=2500)),
                ('budget', models.FloatField(null=True)),
                ('suggested_count', models.IntegerField(default=0)),
                ('BoxOfficeCollection', models.FloatField(null=True)),
                ('imageLink', models.CharField(max_length=2500)),
                ('movieViewCount', models.IntegerField(default=0)),
                ('GENRE', models.ManyToManyField(to='show.GENRE')),
                ('cast', models.ManyToManyField(to='cast.cast')),
                ('director', models.ManyToManyField(to='cast.directors')),
                ('language', models.ManyToManyField(to='show.language')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.Show'),
        ),
    ]
