# Generated by Django 2.1.3 on 2019-05-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='cast',
            field=models.ManyToManyField(to='cast.actors'),
        ),
    ]
