# Generated by Django 2.1.2 on 2019-05-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_show_suggested_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='movieViewCount',
            field=models.IntegerField(default=0),
        ),
    ]
