# Generated by Django 2.1.2 on 2019-05-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_visitedshows'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitedshows',
            name='visitedShows',
        ),
        migrations.DeleteModel(
            name='visitedShows',
        ),
    ]
