# Generated by Django 2.1.7 on 2019-05-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20190501_0127'),
        ('groups', '0003_auto_20190501_0415'),
    ]

    operations = [
    ]
