# Generated by Django 2.1.8 on 2019-04-25 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_cust_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_order_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=6)),
                ('payment_status', models.CharField(choices=[('0', 'Processing'), ('1', 'Confirmed'), ('2', 'Cancelled')], default=0, max_length=50)),
                ('order_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Cust_order')),
            ],
        ),
    ]
