# Generated by Django 2.1.8 on 2019-04-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_order_payment',
            name='cust_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
