# Generated by Django 2.1.8 on 2019-04-25 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_cust_order_payment_cust_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust_order_payment',
            old_name='cust_id',
            new_name='customer_id',
        ),
    ]
