# Generated by Django 2.1.8 on 2019-04-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190425_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='cust_order_payment',
            name='payment_date',
            field=models.DateTimeField(default=None),
        ),
    ]
