# Generated by Django 2.1.3 on 2019-04-14 02:56

import Literature.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150)),
                ('blog_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_list_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(blank=True, max_length=50)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('novel', 'Novel'), ('poetry', 'Poetry'), ('sci_fi', 'Science Fiction'), ('drama', 'Drama'), ('horror', 'Horror'), ('thriller', 'Thriller'), ('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('biography', 'Biography'), ('history', 'History'), ('auto_biography', 'Auto-Biography'), ('mystery', 'Mystery'), ('tragedy', 'Tragedy'), ('fantasy', 'Fantasy'), ('fairy_tale', 'Fairy Tale'), ('kids', 'children stories'), ('graphic_novel', 'Graphic Novel'), ('philosophy', 'Philosophy'), ('myth', 'Mythology'), ('comedy', 'Comedy'), ('textbook', 'Textbook'), ('encyclopedia', 'Encyclopedia'), ('academic_journal', 'Academic Journal')], default='novel', max_length=20)),
                ('thumbnail', models.ImageField(blank='True', default='', null=True, upload_to=Literature.models.content_thumbnail_name)),
                ('file', models.FileField(blank=True, null=True, upload_to=Literature.models.content_file_name)),
                ('uploader', models.ForeignKey(blank='True', on_delete=django.db.models.deletion.CASCADE, related_name='work_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AddField(
            model_name='readinglist',
            name='books',
            field=models.ManyToManyField(blank=True, to='Literature.Work', verbose_name='books'),
        ),
        migrations.AddField(
            model_name='readinglist',
            name='related_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['work_title'], name='Literature__work_ti_7dfbe4_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglist',
            index=models.Index(fields=['r_list_name', 'related_user'], name='Literature__r_list__36c65a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readinglist',
            unique_together={('r_list_name', 'related_user')},
        ),
    ]
