export const GET_MOVIES = "GET_MOVIES";
export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";

export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_FAIL = "REGISTER_FAIL";

export const SHOW_USER = "SHOW_USER";

export const GET_SPECIFICMOVIE = "GET_SPECIFICMOVIE";

export const ADD_COMMENT = "ADD_COMMENT";

export const GET_USERPROFILE = "GET_USERPROFILE";

export const EDIT_USERPROFILE = "EDIT_USERPROFILE";

export const GET_GENRES = "GET_GENRES";

export const GET_LANGUAGES = "GET_LANGUAGES";

export const GET_FORMATS = "GET_FORMATS";

export const GET_SNACKS = "GET_SNACKS";

export const GET_THEATRE_LIST = "GET_THEATRE_LIST";

export const GET_TICKET_BOOKING_HISTORY = "GET_TICKET_BOOKING_HISTORY";

export const GET_CITIES = "GET_CITIES";

export const SELECT_CITY = "SELECT_CITY";

export const GET_SHOW_DETAILS = "GET_SHOW_DETAILS";

export const GET_SEATS_BOOKED = "GET_SEATS_BOOKED";

export const GET_SELECTED_SEATS = "GET_SELECTED_SEATS";

export const IN_BOOKING = "IN_BOOKING";

export const BOOK_HISTORY = "BOOK_HISTORY";
