# Generated by Django 2.1.8 on 2019-04-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cust_Cart',
            fields=[
                ('cart_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cust_cart_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(default=0)),
                ('item_price', models.FloatField(default=0)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cust_Cart')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Cuisine_item')),
            ],
        ),
        migrations.CreateModel(
            name='Cust_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total_price', models.FloatField(default=0)),
                ('order_date', models.DateTimeField()),
                ('order_status', models.CharField(choices=[('0', 'Processing'), ('1', 'Confirmed'), ('2', 'Cancelled')], default=0, max_length=50)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Cust_order_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Cuisine_item')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Cust_order')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cust_order_item',
            unique_together={('order_id', 'item_id')},
        ),
        migrations.AlterUniqueTogether(
            name='cust_order',
            unique_together={('id', 'cust_id')},
        ),
    ]
