# Generated by Django 2.1.8 on 2019-04-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cust_order_item',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cust_order_item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='cust_order_item',
            name='order_id',
        ),
        migrations.DeleteModel(
            name='Cust_order_item',
        ),
    ]
