# Generated by Django 2.1.8 on 2019-04-30 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cust_order_item_order_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cust_order_item',
            name='order_item_status',
            field=models.CharField(choices=[('0', 'Processing'), ('1', 'Prepared')], default=0, max_length=50),
        ),
    ]
