# Generated by Django 2.1.4 on 2019-05-01 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_name', models.CharField(max_length=50)),
                ('theatre_address', models.CharField(max_length=250)),
                ('screen_no', models.CharField(max_length=5)),
                ('show_date_and_time', models.DateTimeField()),
                ('seat_no', models.CharField(max_length=50)),
                ('no_of_seats', models.IntegerField()),
                ('price_per_ticket', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('date_and_time_of_booking', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_api_id', models.CharField(max_length=50)),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_genre', models.CharField(max_length=100)),
                ('movie_release_date', models.DateField()),
                ('movie_age_rating', models.CharField(max_length=100)),
                ('movie_duration_mins', models.CharField(max_length=100)),
                ('movie_language', models.CharField(max_length=100)),
                ('movie_actors', models.CharField(max_length=100)),
                ('movie_directors', models.CharField(max_length=100)),
                ('movie_producers', models.CharField(max_length=100)),
                ('movie_writers', models.CharField(max_length=100)),
                ('imdb_movie_rating', models.CharField(max_length=50)),
                ('movie_description', models.TextField()),
                ('movie_trailer_link', models.CharField(max_length=100)),
                ('movie_poster_1', models.ImageField(blank=True, upload_to='poster_1')),
                ('movie_poster_2', models.ImageField(blank=True, upload_to='poster_2')),
            ],
        ),
        migrations.CreateModel(
            name='movie_search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_date', models.DateTimeField()),
                ('no_of_searches', models.IntegerField()),
                ('movie_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='movie_id', to='movies_and_cinemas.movie')),
            ],
        ),
        migrations.CreateModel(
            name='screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_api_id', models.CharField(max_length=50)),
                ('screen_no', models.CharField(max_length=5)),
                ('seat_string', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theatre_api_id', models.CharField(max_length=50)),
                ('theatre_name', models.CharField(max_length=50)),
                ('adressline1', models.CharField(max_length=50)),
                ('adressline2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('theatre_rating', models.CharField(max_length=50)),
                ('no_of_screens', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_price_and_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_api_id', models.CharField(max_length=50)),
                ('show_timings', models.TimeField()),
                ('date', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('screen_type', models.CharField(max_length=50)),
                ('seat_class', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=100)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies_and_cinemas.movie')),
                ('screen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_and_cinemas.screen')),
            ],
        ),
        migrations.CreateModel(
            name='update_on_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='update_on_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_on_movie', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='update_on_screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_on_screen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='update_on_theatre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_on_theatre', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='update_on_ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update_on_ticket', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='theatre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_and_cinemas.theatre'),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='movie_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies_and_cinemas.movie'),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
