# Generated by Django 2.1.4 on 2019-05-01 05:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_cinemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('ticket_id', models.CharField(max_length=50)),
                ('selected_seats', models.CharField(max_length=50)),
                ('date_and_time', models.DateTimeField(default=datetime.datetime(2019, 5, 1, 5, 59, 2, 652757, tzinfo=utc))),
                ('price', models.IntegerField()),
                ('txn_status', models.CharField(max_length=50)),
            ],
        ),
    ]
