# Generated by Django 2.1.1 on 2018-12-11 16:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pending_redeem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField(default=666781, unique=True)),
                ('transaction_id', models.CharField(default='05E0AC5AC000', max_length=14)),
                ('user', models.CharField(max_length=30)),
                ('redeem_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pending_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(default=0, max_length=12, unique=True)),
                ('transaction_id', models.CharField(default='ADD87AA1DD99', max_length=14)),
                ('user', models.CharField(max_length=30)),
                ('pending_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(default=0)),
                ('transaction_id', models.CharField(max_length=12)),
                ('user', models.CharField(max_length=30)),
            ],
        ),
    ]
