# Generated by Django 2.2 on 2019-04-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0012_auto_20190429_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='587A7E92B68E', max_length=14),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='ADD35A9472A4', max_length=14),
        ),
    ]
