# Generated by Django 2.2 on 2019-05-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0014_auto_20190430_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pending_redeem',
            name='transaction_id',
            field=models.CharField(default='7BC087C55038', max_length=14),
        ),
        migrations.AlterField(
            model_name='pending_transactions',
            name='transaction_id',
            field=models.CharField(default='ADD4B393346D', max_length=14),
        ),
    ]
