# Generated by Django 2.1.3 on 2019-05-01 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '0001_initial'),
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episodeNum', models.IntegerField()),
                ('episodeName', models.CharField(max_length=50, null=True)),
                ('releaseDate', models.CharField(max_length=100)),
                ('runTime', models.DurationField()),
                ('episodePoster', models.CharField(max_length=1000)),
                ('episodeSummary', models.CharField(max_length=2500)),
                ('cast', models.ManyToManyField(to='cast.cast')),
                ('episodeReview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.review')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seasonNum', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleName', models.CharField(max_length=120)),
                ('seriesSummary', models.CharField(max_length=2500)),
                ('seriesPoster', models.CharField(max_length=1000)),
                ('seriesViewCount', models.IntegerField(default=0)),
                ('GENRE', models.ManyToManyField(to='show.GENRE')),
                ('language', models.ManyToManyField(to='show.language')),
                ('seriesReview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='show.review')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tvshow.Season'),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tvshow.TVShow'),
        ),
    ]
