# Generated by Django 2.1.7 on 2019-04-30 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user_name',
        ),
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
