# Generated by Django 2.1.7 on 2019-04-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_reviews', '0003_auto_20190430_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
