# Generated by Django 2.1.7 on 2019-04-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_reviews', '0004_rate_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='likes',
        ),
    ]
