# Generated by Django 2.1.7 on 2019-04-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190405_2221'),
        ('group', '0003_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterUniqueTogether(
            name='group_members',
            unique_together={('group_id', 'user_id')},
        ),
    ]
