# Generated by Django 2.1.7 on 2019-04-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_auto_20190406_0537'),
        ('group', '0004_auto_20190406_1042'),
    ]

    operations = [
    ]
