# Generated by Django 2.1.7 on 2019-04-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_merge_20190406_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
    ]
