# Generated by Django 2.1.7 on 2019-04-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190405_2221'),
        ('group', '0006_remove_event_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group_members',
            new_name='GroupMembers',
        ),
    ]
