# Generated by Django 2.1.7 on 2019-04-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_group_affiliation_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_affiliation_archive',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Profile'),
        ),
    ]
