# Generated by Django 2.1.7 on 2019-04-07 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_auto_20190407_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arch_Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='group_affiliation_archive',
            name='group',
        ),
        migrations.RemoveField(
            model_name='group_affiliation_archive',
            name='member',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='group_affiliation_archive',
        ),
        migrations.AlterUniqueTogether(
            name='arch_event',
            unique_together={('name', 'group_id')},
        ),
    ]
