# Generated by Django 2.1.7 on 2019-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20190407_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
