# Generated by Django 2.1.7 on 2019-04-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0014_auto_20190414_0534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventforum',
            name='comment',
            field=models.CharField(max_length=2000),
        ),
    ]
