# Generated by Django 2.1.7 on 2019-04-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0015_auto_20190414_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventforum',
            name='comment',
            field=models.TextField(),
        ),
    ]
