# Generated by Django 2.2 on 2019-05-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newvolunteer',
            name='Vcity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
