# Generated by Django 2.2 on 2019-04-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_id', models.IntegerField()),
                ('expiry', models.IntegerField()),
                ('tenant_id', models.IntegerField()),
                ('tenant_name', models.CharField(max_length=255)),
                ('floor', models.IntegerField()),
                ('ad_desc', models.CharField(max_length=255)),
                ('deal', models.FloatField()),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
    ]
